# Generated by Django 5.2 on 2025-05-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=120)),
            ],
        ),
    ]
